<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <Platforms>x64</Platforms>
        <DebugType>embedded</DebugType>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" PrivateAssets="all"  Version="2024.3.0" />
        <PackageReference Include="Microsoft.Build.Utilities.Core" PrivateAssets="all" Version="17.14.28" />
        <PackageReference Include="Microsoft.Build.Framework"         PrivateAssets="all" Version="17.14.28" />
        <PackageReference Include="Mono.Cecil" Version="0.11.6" />
    </ItemGroup>

    <!-- Ensures all copy-local dependencies (like Mono.Cecil.dll) are in bin\ -->
    <Target Name="EnsureWeaverDepsInBin" AfterTargets="Build">
        <ItemGroup>
            <_CopyLocal Include="@(ReferenceCopyLocalPaths)" />
        </ItemGroup>
        <Copy SourceFiles="@(_CopyLocal)" DestinationFolder="$(OutDir)" SkipUnchangedFiles="true" />
    </Target>
</Project>
