<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <OutputType>WinExe</OutputType>
      <TargetFramework>net9.0</TargetFramework>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
      <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
      <Platforms>x64</Platforms>
      <Configurations>Debug;Release</Configurations>
      <PublishAot>true</PublishAot>
      <DebugSymbols>false</DebugSymbols>

      <RuntimeIdentifier>win-x64</RuntimeIdentifier>

      <InvariantGlobalization>true</InvariantGlobalization>
      <StripSymbolsDuringPublish>true</StripSymbolsDuringPublish>
  </PropertyGroup>
</Project>
