<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Platforms>x64</Platforms>
        <DebugType>embedded</DebugType>
        <Configurations>Debug;Release</Configurations>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Shipping'">
        <DebugType>none</DebugType>
        <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Engine.Core\Engine.Core.csproj" />
    </ItemGroup>

</Project>
