<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyVersion>0.1.0.0</AssemblyVersion>
        <FileVersion>0.1.0.0</FileVersion>
        <Company>Tenebrie Interactive</Company>
        <Product>SharpEngine Shipping</Product>
        <Copyright>2025 Tenebrie</Copyright>
    </PropertyGroup>

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Platforms>x64</Platforms>
        <Configurations>Release</Configurations>

        <SelfContained>true</SelfContained>
        <PublishTrimmed>false</PublishTrimmed>
        <PublishReadyToRun>true</PublishReadyToRun>
        <InvariantGlobalization>true</InvariantGlobalization>
        <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Shipping'">
        <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
        <RuntimeIdentifiers>win-x64;linux-x64;osx-arm64</RuntimeIdentifiers>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="..\ProjectRoot\**\*">
            <Link>%(RecursiveDir)%(Filename)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Remove="..\ProjectRoot\README.txt" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="FontStashSharp" Version="1.3.10" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
        <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
        <PackageReference Include="Silk.NET.Input" Version="2.22.0" />
        <PackageReference Include="Silk.NET.Windowing" Version="2.22.0" />
        <PackageReference Include="Microsoft.Direct3D.DXC"
                          Version="1.8.2505.32"
                          GeneratePathProperty="true" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Engine.Core\Engine.Core.csproj" />
        <ProjectReference Include="..\Engine.Main.Shared\Engine.Main.Shared.csproj" />
        <ProjectReference Include="..\Engine.Tooling.Roslyn\Engine.Tooling.Roslyn.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
        <ProjectReference Include="..\Engine.Module.Physics\Engine.Module.Physics.csproj" />
        <ProjectReference Include="..\Engine.Module.Rendering\Engine.Module.Rendering.csproj" />
        <ProjectReference Include="..\Engine.Module.Utility\Engine.Module.Utility.csproj" />
        <ProjectReference Include="..\User.Game\User.Game.csproj" />
    </ItemGroup>

    <Target Name="CopyDxcBinaries" AfterTargets="Build;Publish">
        <ItemGroup>
            <_DxcFiles Include="$(PkgMicrosoft_Direct3D_DXC)\build\native\bin\$(PlatformTarget)\dxcompiler.dll" />
            <_DxcFiles Include="$(PkgMicrosoft_Direct3D_DXC)\build\native\bin\$(PlatformTarget)\dxil.dll" />
        </ItemGroup>

        <Copy SourceFiles="@(_DxcFiles)" DestinationFolder="$(OutDir)" SkipUnchangedFiles="true" />
        <Copy Condition="$(PublishDir) != ''" SourceFiles="@(_DxcFiles)" DestinationFolder="$(PublishDir)" SkipUnchangedFiles="true" />
    </Target>

</Project>
