using System.Security.Cryptography;
using Microsoft.CodeAnalysis;

namespace Engine.Tooling.Roslyn.Generators;

[Generator]
public sealed class ClassHashGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext ctx)
    {
        var candidates = ctx.SyntaxProvider
            .ForAttributeWithMetadataName("Engine.Core.EntitySystem.Attributes.OnPrepareResourcesAttribute",
                static (_, _) => true,
                (context, _) =>
                {
                    var owner = context.TargetSymbol;
                    var type = owner switch
                    {
                        INamedTypeSymbol t => t,
                        _                 => owner.ContainingType!
                    };
                    var tree = context.TargetNode.SyntaxTree;
                    return (Type: type, Tree: tree);
                });
        
        var typedHashes =
            candidates.Select((info, ct) =>
            {
                var bytes = info.Tree.GetText(ct).Encoding!.GetBytes(info.Tree.GetText(ct).ToString());
                var hash  = Convert.ToBase64String(SHA256.Create().ComputeHash(bytes));
                return (info.Type, Hash: hash);
            });
        
        ctx.RegisterSourceOutput(typedHashes, static (spc, data) =>
        {
            var type   = data.Type;
            var ns     = type.ContainingNamespace.IsGlobalNamespace
                ? null
                : $"namespace {type.ContainingNamespace.ToDisplayString()};";
            var name   = type.Name;
            var source =
                $$"""
                // <auto-generated/>
                #line hidden
                {{ns}}
                partial class {{name}}
                {
                    private const string __SourceHash = "{{data.Hash}}";
                }
                """;
            spc.AddSource($"{name}.ResourceHash.g.cs", source);
        });
    }
}