using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Engine.Tooling.Roslyn.Generators;

[Generator]
public sealed class LaminaLayoutCreatorsGenerator : IIncrementalGenerator
{
    private const string LaminaLayoutMetadataName = "Engine.Core.Lamina.LaminaLayout";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var shouldRun = context.CompilationProvider.Select((c, _) =>
            string.Equals(c.AssemblyName, "Engine.Core.Lamina", StringComparison.Ordinal));
        
        var candidateRecords = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is RecordDeclarationSyntax,
            static (ctx, _) => ModelExtensions.GetDeclaredSymbol(ctx.SemanticModel, (RecordDeclarationSyntax)ctx.Node) as INamedTypeSymbol
        ).Where(static s => s is not null)!;

        var layouts = candidateRecords.Where(static s => InheritsFrom(s!, LaminaLayoutMetadataName));
        var input = layouts.Collect().Combine(shouldRun);
        
        context.RegisterSourceOutput(input, static (spc, data) =>
        {
            var (list, run) = data;
            if (!run || list.IsDefaultOrEmpty) return;

            foreach (var group in list.Where(s => s is not null)!.GroupBy(s => s!.ContainingNamespace.ToDisplayString()))
            {
                var ns = group.Key;
                var sb = new StringBuilder();
                // sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("using System;");
                // sb.AppendLine("using Engine.Core.Lamina;");
                sb.AppendLine();
                sb.AppendLine($"namespace {ns};");
                sb.AppendLine();
                sb.AppendLine("public partial record LaminaLayout");
                sb.AppendLine("{");

                foreach (var layout in group)
                {
                    try { AppendCreator(sb, layout!); }
                    catch { /* keep other types generating */ }
                }

                sb.AppendLine("}");
                spc.AddSource($"{Sanitize(ns)}.LaminaLayoutExtensions.g.cs", sb.ToString());
            }
        });
    }

    private static void AppendCreator(StringBuilder sb, INamedTypeSymbol layout)
    {
        // Method name = type name without "Layout" suffix
        var methodName = layout.Name;
        if (methodName.EndsWith("Layout", StringComparison.Ordinal))
            methodName = methodName.Substring(0, methodName.Length - "Layout".Length);

        // Use the primary ctor (the one that corresponds to the record's parameter list)
        var ctor = layout.InstanceConstructors
            .Where(c => c.DeclaringSyntaxReferences.Any(sr =>
                sr.GetSyntax() is RecordDeclarationSyntax r && r.ParameterList is not null))
            .OrderByDescending(c => c.Parameters.Length)
            .FirstOrDefault();

        if (ctor is null) return;

        if (ctor.Parameters.Length == 1 &&
            ctor.Parameters[0].Name.Equals("Props", StringComparison.OrdinalIgnoreCase) &&
            ctor.Parameters[0].Type is INamedTypeSymbol propsType)
        {
            EmitPropsShape(sb, layout, methodName, propsType);
        }
        else
        {
            EmitPositionalShape(sb, layout, methodName, ctor.Parameters);
        }
    }

    private static void EmitPropsShape(StringBuilder sb, INamedTypeSymbol layout, string methodName, INamedTypeSymbol propsType)
    {
#pragma warning disable RS1035
        var newLine = Environment.NewLine;
#pragma warning restore RS1035
        var layoutShort = layout.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        var propsShort  = propsType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);

        var members = propsType.GetMembers()
            .Where(m => !m.IsStatic)
            .Select(m => m switch
            {
                IFieldSymbol f when !f.IsConst && f.DeclaredAccessibility == Accessibility.Public
                    => new Member { Sym = f, Name = f.Name, Type = f.Type, HasInit = HasInitializer(f), Ord = DeclOrder(f) },
                IPropertySymbol p when p.SetMethod is not null && p.DeclaredAccessibility == Accessibility.Public
                    => new Member { Sym = p, Name = p.Name, Type = p.Type, HasInit = HasInitializer(p), Ord = DeclOrder(p) },
                _ => null
            })
            .Where(x => x is not null)!
            .OrderBy(x => x!.Ord)
            .ToArray();
        
        var children = members.SingleOrDefault(m => IsChildrenAction(m!.Sym, m.Type));
        var hasChildren = children is not null;
        // if (hasChildren)
        //     members = members.Where(m => !SymbolEqualityComparer.Default.Equals(m!.Sym, children!.Sym)).ToArray();

        var required = members.Where(m => !m!.HasInit).ToArray();
        var optional = members.Where(m =>  m!.HasInit).ToArray();

        var paramList = string.Join(", ",
            required.Select(ParamSig!).Concat(optional.Select(ParamSig!)));

        var requiredAssignments = string.Join(newLine,
            required.Select(m => $"        props.{m.Name} = {Camel(m.Name)};"));

        var optionalAssignments = string.Join(newLine,
            optional.Select(m =>
            {
                var pname = Camel(m!.Name);
                if (m.Type.IsValueType && !IsNullableType(m.Type))
                    return $"        if ({pname}.HasValue) props.{m.Name} = {pname}.Value;";
                else
                    return $"        if ({pname} is not null) props.{m.Name} = {pname};";
            }));
        
        var addLine = hasChildren
            ? $"Add(new {layoutShort}(props), children)"
            : $"Add(new {layoutShort}(props))";

        sb.AppendLine($@"
    public void {methodName}({paramList})
    {{
        var props = new {propsShort}();
{(requiredAssignments.Length > 0 ? requiredAssignments + newLine : "")}{optionalAssignments}
        {addLine};
    }}");
        return;

        // required first, then optional (with = null)
        string ParamSig(Member m)
        {
            var pname = Camel(m.Name);
            var type = m.HasInit
                ? MakeNullableTypeDisplay(m.Type)
                : m.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var opt = m.HasInit ? " = null" : "";
            return $"{type} {pname}{opt}";
        }
    }

    private static void EmitPositionalShape(StringBuilder sb, INamedTypeSymbol layout, string methodName, ImmutableArray<IParameterSymbol> ps)
    {
        var layoutShort = layout.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);

        // Still a single method; callers can use named args in any order.
        var paramList = string.Join(", ",
            ps.Select(p =>
                $"{p.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)} {Camel(p.Name)}"));

        var argList = string.Join(", ", ps.Select(p => Camel(p.Name)));

        sb.AppendLine($@"
    public void {methodName}({paramList})
    {{
        Add(new {layoutShort}({argList}));
    }}");
    }

    private static bool InheritsFrom(INamedTypeSymbol type, string baseMetadataName)
    {
        for (var t = type.BaseType; t is not null; t = t.BaseType)
        {
            if (t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                  .TrimStart("global::".ToCharArray()) == baseMetadataName)
                return true;
        }
        return false;
    }

    private static string Sanitize(string ns) => ns.Replace('.', '_');
    
    private static string Camel(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        var n = char.ToLowerInvariant(name[0]) + name.Substring(1);
        // escape C# keywords (e.g., "event" → "@event")
        if (SyntaxFacts.GetKeywordKind(n) != SyntaxKind.None) n = "@" + n;
        return n;
    }
    
    private static bool HasInitializer(ISymbol m)
    {
        foreach (var sr in m.DeclaringSyntaxReferences)
        {
            var node = sr.GetSyntax();
            if (node is VariableDeclaratorSyntax v && v.Initializer is not null) return true;
            if (node is PropertyDeclarationSyntax p && p.Initializer is not null) return true;
        }
        return false;
    }

    private static bool IsNullableType(ITypeSymbol t)
        => t.OriginalDefinition.SpecialType == SpecialType.System_Nullable_T;

    private static string MakeNullableTypeDisplay(ITypeSymbol t)
    {
        var s = t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        if (t.IsReferenceType)
            return s.EndsWith("?") ? s : s + "?";
        if (IsNullableType(t))
            return s;
        return s + "?"; // Nullable<T> via ?
    }
    
    private static int DeclOrder(ISymbol s)
    {
        var loc = s.Locations.FirstOrDefault(l => l.IsInSource);
        return loc != null ? loc.SourceSpan.Start : int.MaxValue;
    }
    
    private sealed class Member
    {
        public ISymbol Sym { get; set; } = null!;
        public string Name { get; set; } = "";
        public ITypeSymbol Type { get; set; } = null!;
        public bool HasInit { get; set; }
        public int Ord { get; set; }
    }
    
    private static bool IsChildrenAction(ISymbol sym, ITypeSymbol type)
    {
        if (sym.Name != "Children") return false;
        var t = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return t == "global::System.Action<global::Engine.Core.Lamina.LaminaLayout>";
    }
}
